[package]
name = "twitter-space-tts"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.11", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
