[package]
name = "twitter-space-tts"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3.4.0"
portaudio = "0.7.0"
reqwest = { version = "0.11.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
