name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release
      - run: |
          cd target/release
          tar zcvf twitter-space-tts-macos-0.1.0.tar.gz twitter-space-tts
          mv twitter-space-tts-macos-0.1.0.tar.gz ../..
      - uses: softprops/action-gh-release@v1
        with:
          files: twitter-space-tts-macos-0.1.0.tar.gz
